#!/usr/bin/env raku

=begin pod

=head1 tools/paradigms.raku

Every verb in the lexicon, inflected across the cells Kevin asked for on
2026-07-28: past, present, future, command, question, might, and negative.

Writes C<build/paradigms.toml>, which C<tools/build_dictionary.py> renders into
the dictionary page.

=head2 Why this crosses a language boundary

The split decided on 2026-07-28 gives Raku the language and Python the type
technology, and a paradigm needs both. Choosing C<-se> over C<-so> is
morphology, so it happens here. Turning a form into private-use code points with
a font embedded beside them is typography, so it happens there.

This is a computed result rather than a mirror of a declaration, which is the
distinction that makes the handoff acceptable. Nothing here is stated anywhere
else: delete the file and the next build recreates it identically.

TOML rather than JSON because both sides already read it, Python natively.

=end pod

use Ronosathwasha::Chatbot;
use Ronosathwasha::Types;
use Ronosathwasha::Script;
use Ronosathwasha::Lexicon;
use Ronosathwasha::Morphology;
use Ronosathwasha::Harmony;
use Ronosathwasha::Realizer;

#| Recover the stem a verb inflects on.
#|
#| The lexicon lists most verbs by their infinitive, because that is the form a
#| speaker would offer if asked for the word. `medi`, `tonə` and the `-ya`
#| cognitive roots are listed bare, so anything without an infinitive marker is
#| already a stem.
sub stem-of(Morphology:D $morphology, Str:D $form --> Str) {
    my @markers = $morphology.by-id('infinitive').forms;

    with @markers.first({ $form.ends-with($_) && $form.chars > .chars }) -> $marker {
        return $form.substr(0, $form.chars - $marker.chars);
    }

    $form;
}

sub escape(Str:D $s --> Str) { '"' ~ $s.subst('\\', '\\\\', :g).subst('"', '\\"', :g) ~ '"' }

sub MAIN() {
    my IO::Path $root = repository-root;
    my IO::Path $data = $root.add('data');

    my $script     = load-script($data.add('script.toml'));
    my $morphology = load-morphology($data.add('morphology.toml'));
    my $lexicon    = load-lexicon($data.add('lexicon.toml'));

    my @rows;
    my %seen;

    for $lexicon.in-section('verb') -> $entry {
        my Str $stem = stem-of($morphology, $entry.roman);

        next if %seen{$stem}++;

        my $class = profile-of($script, $stem);

        # A disharmonic stem has no class for an affix to agree with, so it has
        # no paradigm. There are none today and the test asserts it; reporting
        # rather than skipping means a future one is visible instead of absent.
        if $class == MixedWord {
            note "skipped $stem: neither front nor back";
            next;
        }

        my %cells = paradigm($script, $morphology, $stem).Hash;

        @rows.push: %(
            stem  => $stem,
            gloss => $entry.gloss,
            class => $class.key,
            cells => %cells,
        );
    }

    my $out = $root.add('build').add('paradigms.toml');
    $out.parent.mkdir;

    my @order = <past present future command question might negative>;

    my $toml = qq:to/HEAD/;
    # Generated by tools/paradigms.raku. Do not edit.
    #
    # Every verb stem in the lexicon, inflected. The cells are chosen by the
    # stem's own harmony class, so a front verb and a back verb differ in every
    # column, and the negator disagrees with both on purpose.

    cells = [{ @order.map({ escape($_) }).join(', ') }]

    HEAD

    for @rows -> %row {
        $toml ~= "[[verb]]\n";
        $toml ~= "stem = { escape(%row<stem>) }\n";
        $toml ~= "gloss = { escape(%row<gloss>) }\n";
        $toml ~= "harmony = { escape(%row<class>) }\n";

        for @order -> $cell {
            $toml ~= "$cell = { escape(%row<cells>{$cell}) }\n";
        }

        $toml ~= "\n";
    }

    $out.spurt($toml);

    say "{ $out.relative($root) }: { @rows.elems } verbs, { @order.elems } cells each";
}
